# This workflow will do a clean install of node dependencies, build the source code and push the binaries to the deployment repository.
name: Build & deploy web wallet

on:
    push:
        branches: [rebrand]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.13.1
              uses: actions/setup-node@v1
              with:
                  node-version: 16.13.1
            - run: corepack enable
            - run: yarn install --network-concurrency 1 --frozen-lockfile
            - run: yarn run build-hash
            - uses: actions/upload-artifact@v4
              with:
                  name: build-hash-binaries
                  path: build/hash-history

    deployment:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.ref_name }}

        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: build-hash-binaries
                  path: build/hash-history
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                  REPO: self
                  BRANCH: ${{ steps.extract_branch.outputs.branch }}-dist
                  FOLDER: build/hash-history
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
